import Link from "next/link";
import { CalendarDays, ChevronRight, Clock3, RotateCcw } from "lucide-react";
import type { Order } from "@/types";
import { formatPrice } from "@/lib/utils";
import { StatusBadge } from "@/components/ui/StatusBadge";

export function OrderCard({ order }: { order: Order }) {
  return <article className="card group relative overflow-hidden p-5 md:p-6"><span className="absolute inset-y-5 left-0 w-1 rounded-r-full bg-[#FFE394] opacity-0 transition group-hover:opacity-100"/><div className="flex items-start justify-between gap-3"><div className="min-w-0"><span className="text-[9px] font-extrabold tracking-[.12em] text-[#8a9692]">{order.id}</span><h3 className="mt-1 truncate text-[15px] font-black">{order.serviceName}</h3><p className="mt-0.5 text-xs text-[#667085]">{order.packageName}</p></div><StatusBadge status={order.status}/></div><div className="my-4 flex flex-wrap gap-x-4 gap-y-2 rounded-2xl bg-[#EEEEEE] px-3.5 py-3 text-xs font-semibold text-[#667085]"><span className="flex items-center gap-1.5"><CalendarDays size={14} className="text-[#2FA084]"/>{order.date}</span><span className="flex items-center gap-1.5"><Clock3 size={14} className="text-[#2FA084]"/>{order.time} WIB</span></div><div className="flex items-center justify-between"><div><span className="block text-[9px] font-semibold tracking-wide text-[#8a9692]">TOTAL BAYAR</span><b className="mt-0.5 block text-[15px]">{formatPrice(order.totalPrice)}</b></div><div className="flex gap-2">{["completed", "cancelled"].includes(order.status) && <Link href={`/booking/${order.serviceId}`} className="pressable grid size-10 place-items-center rounded-xl border border-[#D8DEDA] bg-white" aria-label="Pesan lagi"><RotateCcw size={16}/></Link>}<Link href={`/orders/${order.id}`} className="inline-flex h-10 items-center gap-1 rounded-xl bg-[#2FA084] px-3.5 text-xs font-extrabold text-white shadow-[0_6px_16px_rgba(31,111,95,.14)] transition hover:bg-[#195A4D] active:scale-95">Lihat detail <ChevronRight size={14}/></Link></div></div></article>;
}
