"use client";
import { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Banknote, Building, CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, CreditCard, Home, MapPin, QrCode, ShieldCheck, Smartphone, Sparkles, UserRound, UsersRound, WalletCards, Zap } from "lucide-react";
import { readClientService, readPaymentMethods } from "@/lib/localData";
import { cn, formatPrice } from "@/lib/utils";
import { Button } from "@/components/ui/Button";
import { PackageCard } from "@/components/services/PackageCard";
import { BookingStepper } from "./BookingStepper";
import { PriceSummary } from "./PriceSummary";

const dates = [{day:"Sel",date:"30",month:"Jun"},{day:"Rab",date:"01",month:"Jul"},{day:"Kam",date:"02",month:"Jul"},{day:"Jum",date:"03",month:"Jul"},{day:"Sab",date:"04",month:"Jul"}];
const times = ["08.00", "10.00", "12.00", "14.00", "16.00"];
const Field = ({label, placeholder, value}: {label:string; placeholder:string; value?:string}) => <label className="block"><span className="mb-2 block text-xs font-extrabold">{label}</span><input defaultValue={value} placeholder={placeholder} className="h-13 w-full rounded-2xl border border-[#D8DEDA] bg-[#fbfcfc] px-4 text-sm outline-none transition-all focus:border-[#608d81] focus:bg-white focus:shadow-[0_8px_22px_rgba(31,111,95,.07)] focus:ring-3 focus:ring-[#FFE394]/60"/></label>;
const Choice = ({selected,onClick,icon:Icon,title,desc,disabled}: {selected:boolean;onClick:()=>void;icon:typeof Home;title:string;desc:string;disabled?:boolean}) => <button disabled={disabled} onClick={onClick} className={cn("pressable flex w-full items-center gap-3.5 rounded-[20px] border p-4 text-left", selected ? "border-[#2FA084] bg-[#fbffef] shadow-[0_7px_18px_rgba(31,111,95,.07)] ring-2 ring-[#FFE394]" : "border-[#D8DEDA] bg-white hover:border-[#cbd8d3]", disabled && "opacity-40")}><span className={cn("grid size-11 shrink-0 place-items-center rounded-[14px] transition-colors",selected?"bg-[#2FA084] text-[#FFE394]":"bg-[#f0f3f2] text-[#64736e]")}><Icon size={19}/></span><span className="min-w-0 flex-1"><b className="block text-sm font-extrabold">{title}</b><span className="mt-0.5 block text-[11px] leading-4 text-[#74817d]">{desc}</span></span><span className={cn("grid size-5 place-items-center rounded-full border transition-all",selected?"scale-110 border-[#2FA084] bg-[#2FA084] text-white":"border-[#cdd7d3]")}>{selected&&<Check size={12} strokeWidth={3}/>}</span></button>;

export function BookingFlow({ serviceId }: { serviceId?: string }) {
  const router = useRouter(); const params = useSearchParams(); const requestedServiceId = serviceId ?? params.get("service") ?? "home-cleaning"; const [service,setService]=useState(()=>readClientService(requestedServiceId));
  const [step,setStep] = useState(0); const [pkg,setPkg] = useState(service.packages[1]?.id ?? service.packages[0].id); const [addons,setAddons] = useState<string[]>([]); const [date,setDate] = useState(1); const [time,setTime] = useState("10.00"); const [urgent,setUrgent] = useState(false); const [worker,setWorker] = useState("regular"); const [team,setTeam] = useState("1 Partner"); const [payment,setPayment] = useState("QRIS"); const [paymentMethods,setPaymentMethods]=useState(()=>readPaymentMethods()); const [terms,setTerms] = useState(false); const [loading,setLoading] = useState(false);
  useEffect(()=>{const load=()=>{const next=readClientService(requestedServiceId);setService(next);setPkg(next.packages[1]?.id ?? next.packages[0]?.id ?? "");setAddons([]);};load();window.addEventListener("ride-n-care-services-updated",load);window.addEventListener("storage",load);return()=>{window.removeEventListener("ride-n-care-services-updated",load);window.removeEventListener("storage",load);};},[requestedServiceId]);
  useEffect(()=>{const load=()=>{const methods=readPaymentMethods();setPaymentMethods(methods);const first=methods.find((method)=>method.enabled)?.name;if(first&&!methods.some((method)=>method.name===payment&&method.enabled))setPayment(first);};load();window.addEventListener("ride-n-care-payment-methods-updated",load);window.addEventListener("storage",load);return()=>{window.removeEventListener("ride-n-care-payment-methods-updated",load);window.removeEventListener("storage",load);};},[payment]);
  const selectedPackage = service.packages.find((p)=>p.id===pkg) ?? service.packages[0] ?? { id: "custom", name: "Custom Care", price: service.startingPrice, duration: service.duration, description: "Paket custom", features: ["Konsultasi kebutuhan"] }; const addOnPrice = service.addOns.filter((a)=>addons.includes(a.id)).reduce((a,b)=>a+b.price,0); const premiumFee = worker === "premium" ? 35000 : worker === "female" ? 10000 : 0; const urgentFee = urgent ? 25000 : 0; const total = selectedPackage.price+addOnPrice+premiumFee+urgentFee+5000;
  const next = () => setStep((s)=>Math.min(5,s+1)); const back = () => step === 0 ? router.back() : setStep((s)=>s-1); const confirm = () => { setLoading(true); setTimeout(()=>router.push("/orders/ORD-001?new=1"),900); };
  const content = (() => {
    if(step===0) return <><SectionTitle eyebrow="LANGKAH 1" title="Pilih paket care yang paling pas" desc="Mulai dari kebutuhan utama—tambahan care bisa dipilih setelahnya."/><div className="grid gap-3 md:grid-cols-3">{service.packages.map((item)=><PackageCard key={item.id} item={item} selected={pkg===item.id} onSelect={()=>setPkg(item.id)}/>)}</div><div className="mb-3 mt-8"><h3 className="font-extrabold">Butuh care tambahan?</h3><p className="mt-1 text-xs text-[#7a8783]">Tambahkan layanan ekstra sesuai kebutuhan lokasimu.</p></div><div className="grid gap-3 md:grid-cols-2">{service.addOns.map((item)=>{const active=addons.includes(item.id); return <button key={item.id} onClick={()=>setAddons(active?addons.filter((x)=>x!==item.id):[...addons,item.id])} className={cn("pressable flex items-center gap-3 rounded-[18px] border p-4 text-left",active?"border-[#2FA084] bg-[#fbffef] ring-2 ring-[#FFE394]":"border-[#D8DEDA] bg-white")}><span className={cn("grid size-7 place-items-center rounded-lg border transition-all",active?"border-[#2FA084] bg-[#2FA084] text-white":"border-[#cdd7d3]")}>{active&&<Check size={14} strokeWidth={3}/>}</span><span className="flex-1"><b className="block text-sm">{item.name}</b><span className="text-[11px] text-[#77847f]">Tambah waktu {item.duration}</span></span><b className="text-xs">+{formatPrice(item.price)}</b></button>})}</div></>;
    if(step===1) return <><SectionTitle eyebrow="LANGKAH 2" title="Kami datang ke mana?" desc="Pastikan alamat lengkap agar partner mudah menemukanmu."/><div className="mb-5 grid grid-cols-2 gap-3"><Choice selected icon={Home} title="Rumah" desc="Alamat utama" onClick={()=>{}}/><Choice selected={false} icon={Building} title="Kantor" desc="Alamat lainnya" onClick={()=>{}}/></div><div className="grid gap-4 md:grid-cols-2"><Field label="Alamat lengkap" placeholder="Nama jalan, area, kota" value="Jl. Siliwangi, Cianjur"/><Field label="Nomor rumah / unit" placeholder="Contoh: No. 28" value="No. 28"/></div><label className="mt-4 block"><span className="mb-2 block text-xs font-bold">Catatan untuk partner</span><textarea defaultValue="Rumah pagar hijau, tekan bel di samping garasi." className="min-h-24 w-full resize-none rounded-2xl border border-[#D8DEDA] bg-white p-4 text-sm outline-none focus:border-[#608d81]"/></label><div className="mt-4 flex h-36 items-center justify-center rounded-3xl bg-[#e8efec] text-center text-[#61706b]"><span><MapPin className="mx-auto mb-2"/><b className="text-xs">Pratinjau peta</b><small className="block">Integrasi peta akan tersedia nanti</small></span></div><label className="mt-4 flex items-center gap-3 text-xs font-semibold"><input type="checkbox" defaultChecked className="size-4 accent-[#2FA084]"/>Simpan alamat ini sebagai Rumah</label></>;
    if(step===2) return <><SectionTitle eyebrow="LANGKAH 3" title="Kapan partner boleh datang?" desc="Pilih waktu yang paling nyaman. Partner tiba dalam rentang ±15 menit."/><div className="hide-scrollbar flex gap-3 overflow-x-auto pb-2">{dates.map((d,i)=><button key={d.date} onClick={()=>setDate(i)} className={cn("pressable min-w-20 rounded-[18px] border p-3 text-center",date===i?"border-[#2FA084] bg-[#2FA084] text-white shadow-[0_8px_18px_rgba(31,111,95,.16)]":"border-[#e3e9e6] bg-white")}><span className="block text-[10px] font-semibold opacity-70">{d.day}</span><b className="my-1 block text-xl">{d.date}</b><span className="text-[10px] opacity-70">{d.month}</span></button>)}</div><h3 className="mb-3 mt-6 text-sm font-extrabold">Jam kedatangan</h3><div className="grid grid-cols-3 gap-3 md:grid-cols-5">{times.map((item)=><button key={item} onClick={()=>setTime(item)} className={cn("pressable h-12 rounded-2xl border text-sm font-extrabold",time===item?"border-[#2FA084] bg-[#FFF6DE] shadow-[0_6px_14px_rgba(116,149,36,.1)]":"border-[#e3e9e6] bg-white")}>{item}</button>)}</div><div className="mt-6 grid gap-3 md:grid-cols-2"><Choice selected={urgent} icon={Zap} title="Butuh cepat" desc="Prioritas pencarian partner sekarang · +Rp25rb" onClick={()=>setUrgent(!urgent)}/><Choice selected={!urgent} icon={Clock3} title="Waktu fleksibel" desc="Jadwal boleh bergeser hingga 60 menit" onClick={()=>setUrgent(false)}/></div></>;
    if(step===3) return <><SectionTitle eyebrow="LANGKAH 4" title="Preferensi partner" desc="Kami mencocokkan preferensimu dengan partner terbaik yang tersedia."/><div className="space-y-3"><Choice selected={worker==="regular"} icon={UserRound} title="Partner reguler" desc="Terverifikasi dan berpengalaman · Tanpa biaya tambahan" onClick={()=>setWorker("regular")}/><Choice selected={worker==="premium"} icon={Sparkles} title="Partner premium" desc="Rating 4,9+ dan minimal 200 pekerjaan · +Rp35rb" onClick={()=>setWorker("premium")}/><Choice selected={worker==="female"} icon={ShieldCheck} title="Partner perempuan" desc="Tergantung ketersediaan · +Rp10rb" onClick={()=>setWorker("female")}/></div><h3 className="mb-3 mt-6 text-sm font-extrabold">Jumlah partner</h3><div className="flex gap-3">{["1 Partner","2 Partner","Tim 3"].map((item)=><button onClick={()=>setTeam(item)} key={item} className={cn("flex-1 rounded-2xl border py-3 text-xs font-bold",team===item?"border-[#2FA084] bg-[#FFF6DE]":"border-[#e3e9e6] bg-white")}>{item}</button>)}</div><label className="mt-6 block"><span className="mb-2 block text-xs font-bold">Catatan tambahan (opsional)</span><textarea placeholder="Ada hal yang perlu partner ketahui?" className="min-h-24 w-full resize-none rounded-2xl border border-[#D8DEDA] bg-white p-4 text-sm outline-none"/></label></>;
    if(step===4) return <><SectionTitle eyebrow="LANGKAH 5" title="Pilih cara pembayaran" desc="Transaksi aman dan harga sudah transparan."/><div className="space-y-3">{paymentMethods.map((method)=>{const icon = method.name.toLowerCase().includes("qris") ? QrCode : method.name.toLowerCase().includes("tunai") ? Banknote : method.name.toLowerCase().includes("wallet") ? Smartphone : method.name.toLowerCase().includes("nanti") ? WalletCards : CreditCard; return <Choice key={method.id} selected={payment===method.name} disabled={!method.enabled} icon={icon} title={method.name} desc={method.description || (method.enabled ? "Tersedia untuk pembayaran customer" : "Segera hadir")} onClick={()=>setPayment(method.name)}/>})}</div></>;
    return <><SectionTitle eyebrow="LANGKAH 6" title="Cek lagi, lalu konfirmasi" desc="Pastikan semua detail care sudah sesuai sebelum dikonfirmasi."/><div className="space-y-3"><ReviewRow icon={Sparkles} label="Layanan" value={`${service.name} · ${selectedPackage.name}`} action={()=>setStep(0)}/><ReviewRow icon={MapPin} label="Alamat" value="Jl. Siliwangi No. 28, Cianjur" action={()=>setStep(1)}/><ReviewRow icon={CalendarDays} label="Jadwal" value={`${dates[date].day}, ${dates[date].date} ${dates[date].month} · ${time}`} action={()=>setStep(2)}/><ReviewRow icon={UsersRound} label="Partner" value={`${worker === "premium" ? "Premium" : worker === "female" ? "Perempuan" : "Reguler"} · ${team}`} action={()=>setStep(3)}/><ReviewRow icon={QrCode} label="Pembayaran" value={payment} action={()=>setStep(4)}/></div><div className="mt-6 flex gap-3"><input className="mt-1 size-4 shrink-0 accent-[#2FA084]" type="checkbox" checked={terms} onChange={(e)=>setTerms(e.target.checked)}/><p className="text-xs leading-5 text-[#667085]">Saya menyetujui syarat layanan, kebijakan pembatalan, dan penggunaan data untuk memproses pesanan.</p></div></>;
  })();
  return <div className="pb-24 lg:pb-0"><BookingStepper step={step}/><div className="mt-5 grid gap-6 lg:mt-6 lg:grid-cols-[1fr_310px]"><section className="card overflow-hidden p-5 shadow-[0_10px_34px_rgba(31,111,95,.055)] md:p-8"><div key={step} className="booking-panel">{content}</div><div className="mt-8 flex gap-3 border-t border-[#e9eeec] pt-5"><Button variant="ghost" onClick={back} className="px-4"><ChevronLeft size={17}/><span className="hidden sm:inline">Kembali</span></Button>{step<5?<Button onClick={next} className="ml-auto min-w-36">Lanjutkan <ChevronRight size={17}/></Button>:<Button disabled={!terms||loading} onClick={confirm} className="ml-auto min-w-48">{loading?"Sedang menyiapkan...":`Konfirmasi · ${formatPrice(total)}`}</Button>}</div></section><aside className="hidden h-fit lg:sticky lg:top-6 lg:block"><PriceSummary packagePrice={selectedPackage.price} addOnPrice={addOnPrice+urgentFee} premiumFee={premiumFee}/></aside></div><div className="fixed inset-x-0 bottom-0 z-40 border-t border-[#e0e8e4] bg-white/92 px-4 py-3 shadow-[0_-10px_35px_rgba(31,111,95,.10)] backdrop-blur-xl lg:hidden"><div className="mx-auto max-w-lg"><PriceSummary compact packagePrice={selectedPackage.price} addOnPrice={addOnPrice+urgentFee} premiumFee={premiumFee}/></div></div></div>;
}
function SectionTitle({eyebrow,title,desc}:{eyebrow:string;title:string;desc:string}){return <div className="mb-7"><span className="text-[9px] font-black tracking-[.18em] text-[#2FA084]">{eyebrow}</span><h1 className="mt-1.5 text-[25px] font-black leading-tight tracking-[-.025em]">{title}</h1><p className="mt-2 max-w-xl text-sm leading-6 text-[#667085]">{desc}</p></div>}
function ReviewRow({icon:Icon,label,value,action}:{icon:typeof Home;label:string;value:string;action:()=>void}){return <div className="pressable flex items-center gap-3 rounded-[20px] border border-[#D8DEDA] bg-white p-4"><span className="grid size-11 place-items-center rounded-[14px] bg-[#FFF6DE] text-[#466b21]"><Icon size={18}/></span><span className="min-w-0 flex-1"><small className="block text-[9px] font-extrabold tracking-wide text-[#85918d]">{label.toUpperCase()}</small><b className="mt-0.5 block truncate text-sm">{value}</b></span><button onClick={action} className="rounded-xl bg-[#f1f6f3] px-2.5 py-2 text-[9px] font-black text-[#2FA084] transition active:scale-95">UBAH</button></div>}
