import Link from "next/link";
import { ArrowUpRight, TicketPercent } from "lucide-react";
import { promos } from "@/data/promos";

export function PromoBanner() {
  const promo = promos[0];
  return <div className="soft-grid relative min-h-[178px] overflow-hidden rounded-[24px] bg-gradient-to-br from-[#1F6F5F] to-[#2FA084] p-5 text-white shadow-[0_14px_34px_rgba(31,111,95,.18)] sm:min-h-[186px] sm:rounded-[26px] sm:p-6 md:min-h-64 md:rounded-[30px] md:p-8 md:shadow-[0_20px_55px_rgba(31,111,95,.17)]">
    <div className="relative z-20 max-w-[58%] md:max-w-[62%]"><span className="inline-flex items-center gap-1.5 whitespace-nowrap rounded-full bg-[#F48F68] px-2.5 py-1 text-[7px] font-black tracking-[.12em] text-white shadow-sm sm:text-[8px] md:px-3 md:py-1.5 md:text-[9px]"><TicketPercent size={11}/>{promo.eyebrow}</span><h1 className="mt-2.5 text-[17px] font-black leading-[1.08] tracking-[-.035em] min-[390px]:text-[19px] md:mt-4 md:text-4xl"><span className="block whitespace-nowrap">Care datang langsung</span><span className="block whitespace-nowrap">ke lokasi kamu</span></h1><p className="mt-1.5 text-[7px] font-medium text-white/70 sm:text-[8px] md:mt-2 md:text-xs">{promo.subtitle}</p><div className="mt-2.5 flex items-center gap-2 md:mt-4 md:gap-3"><Link href="/services/home-cleaning" className="inline-flex min-h-8 items-center gap-1.5 whitespace-nowrap rounded-[11px] bg-[#6FCF97] px-3 py-1.5 text-[9px] font-black text-[#1F6F5F] shadow-[0_8px_18px_rgba(31,111,95,.16)] transition-transform duration-150 active:scale-95 sm:text-[10px] md:min-h-11 md:rounded-[14px] md:px-4 md:text-xs">Pakai Promo <ArrowUpRight size={13}/></Link><span className="whitespace-nowrap text-[7px] font-medium text-white/60 sm:text-[8px] md:text-[10px]">Kode: <b className="tracking-wide text-white">{promo.code}</b></span></div></div>
    <div className="absolute -bottom-20 -right-14 z-0 size-56 rounded-full bg-[#8BDFDD]/30 sm:-bottom-20 sm:-right-12 sm:size-60 md:-bottom-24 md:right-[-4%] md:size-80"/><div className="absolute bottom-9 right-3 z-10 grid size-[88px] rotate-6 place-items-center rounded-[25px] border border-white/15 bg-white/14 text-center text-[10px] font-black shadow-[0_12px_28px_rgba(31,111,95,.18)] backdrop-blur-[2px] transition-transform duration-300 hover:rotate-3 sm:bottom-10 sm:right-5 sm:size-24 md:bottom-12 md:right-12 md:size-36 md:rounded-[34px] md:text-sm"><span><b className="block text-[28px] leading-none text-[#FFE394] md:text-4xl">25%</b><span className="mt-1 block text-white">first care</span></span></div><span className="absolute right-10 top-6 size-3 rounded-full bg-[#F48F68] md:right-20 md:top-10"/>
  </div>;
}
